[package]
name = "libproofofwork"
version = "0.1.0"
authors = ["jocular"]
edition = "2018"

[dependencies]
sha2 = "*"
byteorder = "*"

[lib]
name = "proofofwork"
path = "src/lib.rs"
crate-type = ["cdylib", "lib", "staticlib"]